# Generated by Django 2.1.2 on 2019-03-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_auto_20190305_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='id_user',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
    ]
